sudo: required
services:
  - docker

before_install:
  - docker build -t lukstar/deploy_flow -f Dockerfile.dev .

script:
  - docker run -e CI=true lukstar/deploy_flow  npm test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "deploy_flow"
#   env: "deploy_flow_prod"
#   bucket_name: "elasticbeanstalk-us-west-2-323123123123"
#   bucket_path: "deploy_flow"
#   on:
#     branch: master
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"